import { BsToggleOn, BsToggleOff } from "react-icons/bs";
import { TiArrowUnsorted } from "react-icons/ti";

const myterminals = [
  {
    assigned_agent_name: "James Adekola",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "IKEJA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-All TRANSACTIONS",
    status: <BsToggleOn size={20} />,
  },
  {
    assigned_agent_name: "Shola Adeniyi",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "OGBA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-VAS ONLY",
    status: <BsToggleOn size={20} style={{ color: "green" }} />,
  },
  {
    assigned_agent_name: "Tayo Temitope",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "BERGER LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-DEPOSIT ONLY",
    status: <BsToggleOn size={20} />,
  },
  {
    assigned_agent_name: "James Adekola",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "IKEJA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-All TRANSACTIONS",
    status: <BsToggleOn size={20} style={{ color: "green" }} />,
  },
  {
    assigned_agent_name: "Shola Adeniyi",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "OGBA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-VAS ONLY",
    status: <BsToggleOn size={20} />,
  },
  {
    assigned_agent_name: "Tayo Temitope",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "BERGER LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-DEPOSIT ONLY",
    status: <BsToggleOn size={20} style={{ color: "green" }} />,
  },
  {
    assigned_agent_name: "James Adekola",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "IKEJA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-All TRANSACTIONS",
    status: <BsToggleOn size={20} />,
  },
  {
    assigned_agent_name: "Shola Adeniyi",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "OGBA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-VAS ONLY",
    status: <BsToggleOn size={20} style={{ color: "green" }} />,
  },
  {
    assigned_agent_name: "Tayo Temitope",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "BERGER LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-DEPOSIT ONLY",
    status: <BsToggleOn size={20} />,
  },
  {
    assigned_agent_name: "James Adekola",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "IKEJA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-All TRANSACTIONS",
    status: <BsToggleOn size={20} style={{ color: "green" }} />,
  },
  {
    assigned_agent_name: "Shola Adeniyi",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "OGBA, LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-VAS ONLY",
    status: <BsToggleOn size={20} />,
  },
  {
    assigned_agent_name: "Tayo Temitope",
    Agent_id: "N1122567",
    Terminal_id: "N1223245",
    Terminal_location: "BERGER LAGOS STATE",
    Terminal_serial_number: "123456789",
    Terminal_manufacturer: "TM30 GLOBAL INTERNATIONAL",
    Transaction_limit: "500,000",
    Profile: "UP-DEPOSIT ONLY",
    status: <BsToggleOn size={20} style={{ color: "green" }} />,
  },
];

export { myterminals };
